export const LOGIN_SUCCESS: string = 'LOGIN_SUCCESS';
export const LOGIN_ERROR: string = 'LOGIN_ERROR';

export const FETCH_RESTAURANTS_SUCCESS: string = 'FETCH_RESTAURANTS_SUCCESS';
export const FETCH_RESTAURANTS_ERROR: string = 'FETCH_RESTAURANTS_ERROR';

export const FETCH_RESTAURANT_TICKETS_SUCCESS: string = 'FETCH_RESTAURANT_TICKETS_SUCCESS';
export const FETCH_RESTAURANT_TICKETS_ERROR: string = 'FETCH_RESTAURANT_TICKETS_ERROR';
export const FETCH_SINGLE_TICKET_SUCCESS: string = 'FETCH_SINGLE_TICKET_SUCCESS';
export const FETCH_SINGLE_TICKET_ERROR: string = 'FETCH_SINGLE_TICKET_ERROR';
export const EDIT_TICKET_SUCCESS: string = 'EDIT_TICKET_SUCCESS';
export const EDIT_TICKET_ERROR: string = 'EDIT_TICKET_ERROR';
export const DELETE_TICKET_SUCCESS: string = 'DELETE_TICKET_SUCCESS';
export const DELETE_TICKET_ERROR: string = 'DELETE_TICKET_ERROR';
export const SET_EDIT_MODE: string = 'SET_EDIT_MODE';

export const FETCH_TICKET_PURCHASES_SUCCESS: string = 'FETCH_TICKET_PURCHASES_SUCCESS';
export const FETCH_TICKET_PURCHASES_ERROR: string = 'FETCH_TICKET_PURCHASES_ERROR';
export const BUY_TICKET_SUCCESS: string = 'BUY_TICKET_SUCCESS';
export const BUY_TICKET_ERROR: string = 'BUY_TICKET_ERROR';
